kumuluzee:
  name: sledilnik-stevila-obiskovalcev
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/sledilnik-stevila-obiskovalcev
      connection-url: jdbc:postgresql://localhost:5432/sledilnik-stevila-obiskovalcev
      username: postgres
      password: postgres
  security:
    keycloak:
      realm: "master"
      bearer-only: true
      auth-server-url: "http://192.168.99.100:8082/auth"
      ssl-required: "external"
      resource: "sledilnik-stevila-obiskovalcev"
    json: '{
      "realm": "master",
      "bearer-only": true,
      "auth-server-url": "http://192.168.99.100:8082/auth/",
      "ssl-required": "external",
      "resource": "sledilnik-stevila-obiskovalcev-api",
      "confidential-port": 0
    }'
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/sledilnik-stevila-obiskovalcev
  cors-filter:
    servlet:
      allow-generic-http-requests: false
      allow-origin: "*"
integrations:
  sistem-porocil:
    base-url: http://localhost:8081/v1/

