kumuluzee:
  name: sledilnik-stevila-obiskovalcev
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/sledilnik-stevila-obiskovalcev
      connection-url: jdbc:postgresql://192.168.99.100:5432/sledilnik-stevila-obiskovalcev
      username: postgres
      password: postgres